clusterGroupName: tap-vcf
gitrepo: https://github.com/warroyo/tmc-tap-vcf
gitrepo_owner: warroyo
gitrepo_name: tmc-tap-vcf
orgId: d8bdaf07-6e61-4310-92f3-8c52e24a2d54
base_domain: tap-vcf.h2o-4-20916.h2o.vmware.com
issuer_email: william.arroyo@broadcom.com
ako:
  nsxtT1LR: /infra/tier-1s/t1_aae18e07-6764-40cd-89ab-9d936c971f60_rtr
  vipNetworkList:
  - networkName: vcf-ako-net-domain-c8:1ddcbef6-d1c1-4084-8bb3-8c1d3aebd931
    cidr: 10.214.167.176/28
  serviceEngineGroupName: domain-c8:1ddcbef6-d1c1-4084-8bb3-8c1d3aebd931
  cloudName: tanzu
  controllerHost: 10.214.181.32
clusters:
  view:
    mgmt_cluster: mgmt-cluster
    name: tap-view
    provisioner: lab
    cp_count: 3
    worker_count: 3
    worker_vm_class: best-effort-xlarge
    cp_vm_class: best-effort-xlarge
    storage_class: vc01cl01-t0compute
    k8s_version: v1.26.5+vmware.2-fips.1-tkg.1
    kubelet_storage: 100G
    containerd_storage: 100G
    ntp: time2.oc.vmware.com
  build:
    mgmt_cluster: mgmt-cluster
    name: tap-build
    provisioner: lab
    cp_count: 3
    worker_count: 3
    worker_vm_class: best-effort-xlarge
    cp_vm_class: best-effort-xlarge
    storage_class: vc01cl01-t0compute
    k8s_version: v1.26.5+vmware.2-fips.1-tkg.1
    kubelet_storage: 100G
    containerd_storage: 100G
    ntp: time2.oc.vmware.com
  run:
    mgmt_cluster: mgmt-cluster
    name: tap-run
    provisioner: lab
    cp_count: 3
    worker_count: 3
    worker_vm_class: best-effort-xlarge
    cp_vm_class: best-effort-xlarge
    storage_class: vc01cl01-t0compute
    k8s_version: v1.26.5+vmware.2-fips.1-tkg.1
    kubelet_storage: 100G
    containerd_storage: 100G
    ntp: time2.oc.vmware.com
tap:
  version: 1.9.0
  name: tap-vcf
  profiles:
    view:
      ingress_domain: tap-view
      ingress_issuer: step-ca
    build:
      registry:
        server: dev.registry.pivotal.io
        project: warroyo
      clusterCA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ETXlOekl6TWpreU9Gb1hEVE0wTURNeU5USXpNelF5T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG1VCnJJWSthTVEvMHhlTDNReCs0UEhBRVMrcERvdDYvaE5ualM0ZmNFQkwyWE5iaGt3cjlreEJQWGdXYm1WZTR5Z1MKQTFpb1haSjVmNzZBL0txYUtUTEJINTdNV1JvK2NzNVQ4Z3hIc2doemcveXRRMHZiSXcrMkdOUzIrcGNQb29BdgpiQVVMRHFCRTJTVXE2OVhDdnJHMUtIUjhiYXF3QzlxRDhYSXNkalVwMk1BLzZEQTNIR1hLVzRPV0NuRGRMWkIxCjRQSTlJUXkxM1dUNWpacmpWS0I5YjlGb0FKT1NkRGhFemhpNExZUThJdGJubVo2eE9oZU1DNGJoeXM2SEVNaEUKcGpic1lWRzU0Y2F3UGlpZnBSYlM5emhadCt6eDdLdFduTEtIRlNXa3ZlRkpIcy9uaStwTEZZUnlVZ2sxVDJzZQpNdkNnM0x0R2dGUUM4Sm1nQ2NzQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSUNYb1lZUWFvRTRpejlrcFZ5a0I5TFY0S1pMTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQXFWWW5XU0JwMlA2bUMxemJzZlJJaGZEaTM5QTc5UUh4MEtzRnFVQS9lR1puZQoxc3FjTUhhU2ZLQWRtWmVVTFRFZVlNZTAvakpuZVZhTmRtaDlud2ozeWd4eEIvY0ozSDBUbTUxTkRCRE02K3pxCmJSbnM3QnRDN3RWbXMxSWZoREtFWExJOG1JZzFaemt1NStnakw1RjRDVVVJRjUwQXN4bm5teWZBTklQTFpDclYKUGllRWJVRExXbk15VGR5M25qRlAxako2WVlRaFo4ZElmOGxQWTlsTGgxenI0VkZpTm4rWG5vczdKNC9aeE50MApFMFRVelNqR0xERUtkK2RJZ29KTWVJZHhuWVFvSjRZM1BqSlVjdUswdXVteDdWZlNLOFBHcGVHTVRLaUdHWFAxCjFiUGRsbmQ2dDMwM0dqdjJjMGFvTm50a0hRSTRieDJ4Mlg2ZXJ1YzcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      clusterUrl: https://10.214.167.180:6443
    run:
      clusterCA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ETXlOekl6TWpreU9Gb1hEVE0wTURNeU5USXpNelF5T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG1VCnJJWSthTVEvMHhlTDNReCs0UEhBRVMrcERvdDYvaE5ualM0ZmNFQkwyWE5iaGt3cjlreEJQWGdXYm1WZTR5Z1MKQTFpb1haSjVmNzZBL0txYUtUTEJINTdNV1JvK2NzNVQ4Z3hIc2doemcveXRRMHZiSXcrMkdOUzIrcGNQb29BdgpiQVVMRHFCRTJTVXE2OVhDdnJHMUtIUjhiYXF3QzlxRDhYSXNkalVwMk1BLzZEQTNIR1hLVzRPV0NuRGRMWkIxCjRQSTlJUXkxM1dUNWpacmpWS0I5YjlGb0FKT1NkRGhFemhpNExZUThJdGJubVo2eE9oZU1DNGJoeXM2SEVNaEUKcGpic1lWRzU0Y2F3UGlpZnBSYlM5emhadCt6eDdLdFduTEtIRlNXa3ZlRkpIcy9uaStwTEZZUnlVZ2sxVDJzZQpNdkNnM0x0R2dGUUM4Sm1nQ2NzQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSUNYb1lZUWFvRTRpejlrcFZ5a0I5TFY0S1pMTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQXFWWW5XU0JwMlA2bUMxemJzZlJJaGZEaTM5QTc5UUh4MEtzRnFVQS9lR1puZQoxc3FjTUhhU2ZLQWRtWmVVTFRFZVlNZTAvakpuZVZhTmRtaDlud2ozeWd4eEIvY0ozSDBUbTUxTkRCRE02K3pxCmJSbnM3QnRDN3RWbXMxSWZoREtFWExJOG1JZzFaemt1NStnakw1RjRDVVVJRjUwQXN4bm5teWZBTklQTFpDclYKUGllRWJVRExXbk15VGR5M25qRlAxako2WVlRaFo4ZElmOGxQWTlsTGgxenI0VkZpTm4rWG5vczdKNC9aeE50MApFMFRVelNqR0xERUtkK2RJZ29KTWVJZHhuWVFvSjRZM1BqSlVjdUswdXVteDdWZlNLOFBHcGVHTVRLaUdHWFAxCjFiUGRsbmQ2dDMwM0dqdjJjMGFvTm50a0hRSTRieDJ4Mlg2ZXJ1YzcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      clusterUrl: https://10.214.167.180:6443
      ingress_domain: tap-run
      ingress_issuer: step-ca