#@ load("@ytt:data", "data")
server:
  replicaCount: #@ data.values.vault_replicas
  ingress:
    enabled: true
    tls: true
    hostname: #@ data.values.vault_fqdn
    annotations: 
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer