# https://docs.vmware.com/en/VMware-Tanzu-Packages/2024.4.12/tanzu-packages/packages-cert-mgr-super.html#install-cert-manager-using-kubectl-3

--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-sa
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cert-manager-sa
    namespace: cert-manager

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: privileged
spec:
  serviceAccountName: cert-manager-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.7.2+vmware.3-tkg.3
  values:
  - secretRef:
      name: cert-manager-data-values

---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-data-values
  namespace: cert-manager
stringData:
  values.yml: |
    ---
    namespace: cert-manager