# https://docs.vmware.com/en/VMware-Tanzu-Packages/2024.4.12/tanzu-packages/packages-contour-super.html

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tanzu-system-ingress
  labels:
    pod-security.kubernetes.io/enforce: privileged
spec: {}
status: {}